"use strict";
// Minimal smoke test: scaffold into a temp dir, run init+sync+audit, assert outputs exist.
const fs = require("fs");
const os = require("os");
const path = require("path");
const { init, sync, audit, report } = require("../src/commands.js");

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "devrails-test-"));
const origCwd = process.cwd();

function assert(cond, msg) {
  if (!cond) { console.error("FAIL:", msg); process.exitCode = 1; }
  else console.log("PASS:", msg);
}

try {
  process.chdir(tmp);
  init(tmp, { tools: ["agents", "claude", "cursor", "copilot", "gemini"], noGitHook: true, noCi: true, files: [] });

  assert(fs.existsSync(path.join(tmp, ".devrails", "rules", "security.md")), ".devrails source scaffolded");
  assert(fs.existsSync(path.join(tmp, "AGENTS.md")), "AGENTS.md generated");
  assert(fs.existsSync(path.join(tmp, "CLAUDE.md")), "CLAUDE.md generated");
  assert(fs.existsSync(path.join(tmp, "GEMINI.md")), "GEMINI.md generated");
  assert(fs.existsSync(path.join(tmp, ".github", "copilot-instructions.md")), "copilot-instructions.md generated");
  assert(fs.existsSync(path.join(tmp, ".cursor", "rules", "next-js-app-router-patterns.mdc")), "cursor nextjs rule generated");
  assert(fs.existsSync(path.join(tmp, ".github", "instructions", "next-js-app-router-patterns.instructions.md")), "copilot scoped instruction generated");

  // Rich Claude Code target: skills, agents, commands, hooks, settings
  assert(fs.existsSync(path.join(tmp, ".claude", "skills", "next-js-app-router-patterns", "SKILL.md")), "claude skill generated from scoped rule");
  assert(fs.existsSync(path.join(tmp, ".claude", "agents", "code-reviewer.md")), "claude subagent generated");
  assert(fs.existsSync(path.join(tmp, ".claude", "commands", "review.md")), "claude slash command generated");
  assert(fs.existsSync(path.join(tmp, ".claude", "hooks", "pretooluse-secrets.sh")), "claude hook: pretooluse-secrets generated");
  assert(fs.existsSync(path.join(tmp, ".claude", "hooks", "pretooluse-guardian.sh")), "claude hook: pretooluse-guardian generated");
  assert(fs.existsSync(path.join(tmp, ".claude", "hooks", "posttooluse-licenses.sh")), "claude hook: posttooluse-licenses generated");
  assert(fs.existsSync(path.join(tmp, ".claude", "hooks", "posttooluse-logger.sh")), "claude hook: posttooluse-logger generated");
  const settings = JSON.parse(fs.readFileSync(path.join(tmp, ".claude", "settings.json"), "utf8"));
  assert(settings.hooks && settings.hooks.PreToolUse, "claude settings.json wires PreToolUse hooks");
  assert(settings.hooks.PreToolUse.length === 2, "settings.json has 2 PreToolUse hooks (secrets + guardian)");
  assert(settings.hooks.PostToolUse.length === 3, "settings.json has 3 PostToolUse hooks (quality + licenses + logger)");

  // CLAUDE.md holds global rules; scoped ones moved to skills
  const claudeMd = fs.readFileSync(path.join(tmp, "CLAUDE.md"), "utf8");
  assert(/## Security/.test(claudeMd), "global Security rule lands in CLAUDE.md");
  assert(!/## Next\.js App Router Patterns/.test(claudeMd), "scoped Next.js rule is NOT in CLAUDE.md (it's a skill)");

  // Cursor frontmatter should contain globs for the nextjs rule
  const mdc = fs.readFileSync(path.join(tmp, ".cursor", "rules", "next-js-app-router-patterns.mdc"), "utf8");
  assert(/globs: app\/\*\*/.test(mdc), "cursor rule carries globs in frontmatter");
  assert(/alwaysApply: false/.test(mdc), "cursor nextjs rule is glob-scoped (alwaysApply false)");

  // Security rule has empty globs -> alwaysApply true -> lands in copilot main file
  const copilotMain = fs.readFileSync(path.join(tmp, ".github", "copilot-instructions.md"), "utf8");
  assert(/## Security/.test(copilotMain), "global security rule lands in copilot main file");

  // AGENTS.md includes the banner and all four rules
  const agents = fs.readFileSync(path.join(tmp, "AGENTS.md"), "utf8");
  assert(/GENERATED BY devrails/.test(agents), "generated banner present");
  ["Next.js App Router Patterns", "Code Standards", "Accessibility", "Security"].forEach((t) =>
    assert(agents.includes(t), `AGENTS.md includes "${t}"`)
  );

  // re-sync should be idempotent (no throw)
  sync(tmp);
  assert(true, "second sync ran without error");

  // check-code-quality.sh was scaffolded
  assert(
    fs.existsSync(path.join(tmp, ".devrails", "guardrails", "check-code-quality.sh")),
    "check-code-quality guardrail scaffolded"
  );

  // audit on an empty project (no source files) should pass cleanly
  const auditClean = audit(tmp, {});
  assert(auditClean === true, "audit returns true when no source files found");

  // audit detects violations: plant a file with a console.log and `any`
  const srcDir = path.join(tmp, "src");
  fs.mkdirSync(srcDir, { recursive: true });
  fs.writeFileSync(
    path.join(srcDir, "bad.ts"),
    'const x: any = 1;\nconsole.log(x);\n'
  );
  const auditDirty = audit(tmp, {});
  assert(auditDirty === false, "audit returns false when violations are found");

  // audit passes cleanly on a file without violations
  fs.writeFileSync(path.join(srcDir, "bad.ts"), 'const x: unknown = 1;\n');
  const auditFixed = audit(tmp, {});
  assert(auditFixed === true, "audit returns true after violations are fixed");

  // new agents are scaffolded
  [
    "architect.md",
    "tech-writer.md",
    "tdd-red.md",
    "tdd-green.md",
    "tdd-refactor.md",
    "database-reviewer.md",
    "acquire-codebase.md",
    "agent-owasp.md",
    "ai-team.md",
    "prompt-safety.md",
    "autoresearch.md",
    "audit-fix.md",
    "code-exemplars.md",
    "draw-diagram.md",
  ].forEach((f) =>
    assert(fs.existsSync(path.join(tmp, ".claude", "agents", f)), `claude agent scaffolded: ${f}`)
  );

  // new commands are scaffolded
  ["tdd.md", "context-map.md", "refactor-plan.md", "discover.md", "spec-driven.md", "breakdown.md", "llms-txt.md", "git-release.md"].forEach((f) =>
    assert(fs.existsSync(path.join(tmp, ".claude", "commands", f)), `claude command scaffolded: ${f}`)
  );

  // database rule is scaffolded
  assert(fs.existsSync(path.join(tmp, ".devrails", "rules", "database.md")), "database rule scaffolded");

  assert(typeof report === "function", "report is exported");

  // report: with a valid log file
  const logDir = path.join(tmp, "logs", "devrails");
  fs.mkdirSync(logDir, { recursive: true });
  const logFile = path.join(logDir, "session.log");
  fs.writeFileSync(logFile, JSON.stringify({ timestamp: new Date().toISOString(), tool: "Write", file: "src/foo.ts", cwd: tmp }) + "\n");
  // capture stdout
  let reportOut = "";
  const origWrite = process.stdout.write.bind(process.stdout);
  process.stdout.write = (s) => { reportOut += s; return true; };
  report(tmp, {});
  process.stdout.write = origWrite;
  assert(/devrails session report/.test(reportOut), "report generates markdown output");

  console.log("\nGenerated tree:");
  const walk = (d, p = "") => fs.readdirSync(d, { withFileTypes: true }).forEach((e) => {
    if (e.name === ".git") return;
    const rel = path.join(p, e.name);
    console.log("  " + rel);
    if (e.isDirectory()) walk(path.join(d, e.name), rel);
  });
  walk(tmp);
} finally {
  process.chdir(origCwd);
  fs.rmSync(tmp, { recursive: true, force: true });
}
