"use strict";

const fs = require("fs");
const path = require("path");

const GENERATED_BANNER =
  "<!-- GENERATED BY devrails — do not edit by hand. Edit .devrails/rules/ and run `devrails sync`. -->";

function slugify(s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Minimal YAML-subset parser for our controlled frontmatter.
// Supports: key: scalar | key: true/false | key: [a, b, "c"]
function parseYamlSubset(text) {
  const out = {};
  for (const raw of text.split("\n")) {
    const line = raw.trimEnd();
    if (!line || /^\s*#/.test(line)) continue;
    const m = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
    if (!m) continue;
    const key = m[1];
    let val = m[2].trim();
    if (val === "") {
      out[key] = "";
    } else if (val === "true" || val === "false") {
      out[key] = val === "true";
    } else if (val.startsWith("[") && val.endsWith("]")) {
      out[key] = val
        .slice(1, -1)
        .split(",")
        .map((x) => x.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
    } else {
      out[key] = val.replace(/^["']|["']$/g, "");
    }
  }
  return out;
}

function readFrontmatter(content) {
  if (content.startsWith("---")) {
    const end = content.indexOf("\n---", 3);
    if (end !== -1) {
      const fmText = content.slice(3, end).replace(/^\n/, "");
      const body = content.slice(end + 4).replace(/^\n/, "");
      return { data: parseYamlSubset(fmText), body };
    }
  }
  return { data: {}, body: content };
}

function loadRules(devrailsDir) {
  const rulesDir = path.join(devrailsDir, "rules");
  if (!fs.existsSync(rulesDir)) return [];
  return fs
    .readdirSync(rulesDir)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => {
      const full = path.join(rulesDir, f);
      const { data, body } = readFrontmatter(fs.readFileSync(full, "utf8"));
      return {
        file: f,
        slug: slugify(data.title || f.replace(/\.md$/, "")),
        title: data.title || f.replace(/\.md$/, ""),
        description: data.description || "",
        globs: Array.isArray(data.globs) ? data.globs : [],
        alwaysApply: data.alwaysApply === true || (data.globs || []).length === 0,
        body: body.trim(),
      };
    });
}

function loadConfig(devrailsDir) {
  const p = path.join(devrailsDir, "config.json");
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFile(file, content) {
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, content.endsWith("\n") ? content : content + "\n");
  return file;
}

function copyDir(src, dest) {
  ensureDir(dest);
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

// Detect which AI tools are already used in the repo.
function detectTools(cwd) {
  const found = [];
  if (fs.existsSync(path.join(cwd, ".cursor")) || fs.existsSync(path.join(cwd, ".cursorrules")))
    found.push("cursor");
  if (fs.existsSync(path.join(cwd, "CLAUDE.md")) || fs.existsSync(path.join(cwd, ".claude")))
    found.push("claude");
  if (fs.existsSync(path.join(cwd, ".github", "copilot-instructions.md")))
    found.push("copilot");
  if (fs.existsSync(path.join(cwd, "GEMINI.md")) || fs.existsSync(path.join(cwd, ".gemini")))
    found.push("gemini");
  if (fs.existsSync(path.join(cwd, "AGENTS.md"))) found.push("agents");
  return found;
}

const ALL_TARGETS = ["agents", "claude", "cursor", "copilot", "gemini"];

// ---- Project file walker (used by `devrails audit`) --------------------------
const AUDIT_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
const AUDIT_IGNORE_DIRS = new Set([
  "node_modules", ".git", ".devrails", "dist", ".next", "build", "out",
  "coverage", ".turbo", ".cache", ".svelte-kit", "vendor",
]);

function walkProjectFiles(rootDir, extensions = AUDIT_EXTENSIONS, ignoreDirs = AUDIT_IGNORE_DIRS) {
  const results = [];
  function walk(dir) {
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (!ignoreDirs.has(entry.name)) walk(path.join(dir, entry.name));
      } else if (entry.isFile() && extensions.has(path.extname(entry.name))) {
        results.push(path.join(dir, entry.name));
      }
    }
  }
  walk(rootDir);
  return results;
}

module.exports = {
  GENERATED_BANNER,
  ALL_TARGETS,
  slugify,
  parseYamlSubset,
  readFrontmatter,
  loadRules,
  loadConfig,
  ensureDir,
  writeFile,
  copyDir,
  detectTools,
  walkProjectFiles,
};
